/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPostLoginRouteImport } from './routes/_authenticated/post-login'
import { Route as AuthenticatedSupplyDriverRouteRouteImport } from './routes/_authenticated/supply-driver/route'
import { Route as AuthenticatedDriverRouteRouteImport } from './routes/_authenticated/driver/route'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedSupplyDriverIndexRouteImport } from './routes/_authenticated/supply-driver/index'
import { Route as AuthenticatedDriverIndexRouteImport } from './routes/_authenticated/driver/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedSupplyDriverStopsRouteImport } from './routes/_authenticated/supply-driver/stops'
import { Route as AuthenticatedSupplyDriverHistoryRouteImport } from './routes/_authenticated/supply-driver/history'
import { Route as AuthenticatedDriverOverviewRouteImport } from './routes/_authenticated/driver/overview'
import { Route as AuthenticatedDriverExpensesRouteImport } from './routes/_authenticated/driver/expenses'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/app/users'
import { Route as AuthenticatedAppRoutesRouteImport } from './routes/_authenticated/app/routes'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app/reports'
import { Route as AuthenticatedAppProductsRouteImport } from './routes/_authenticated/app/products'
import { Route as AuthenticatedAppPreordersRouteImport } from './routes/_authenticated/app/preorders'
import { Route as AuthenticatedAppPaymentsRouteImport } from './routes/_authenticated/app/payments'
import { Route as AuthenticatedAppLiveRouteImport } from './routes/_authenticated/app/live'
import { Route as AuthenticatedAppExpensesRouteImport } from './routes/_authenticated/app/expenses'
import { Route as AuthenticatedAppDispatchRouteImport } from './routes/_authenticated/app/dispatch'
import { Route as AuthenticatedAppDeliveriesRouteImport } from './routes/_authenticated/app/deliveries'
import { Route as AuthenticatedAppCustomersRouteImport } from './routes/_authenticated/app/customers'
import { Route as AuthenticatedAppBranchesRouteImport } from './routes/_authenticated/app/branches'
import { Route as AuthenticatedAppBodegaRouteImport } from './routes/_authenticated/app/bodega'
import { Route as AuthenticatedAppRoutesIndexRouteImport } from './routes/_authenticated/app/routes.index'
import { Route as AuthenticatedAppRoutesRouteIdRouteImport } from './routes/_authenticated/app/routes.$routeId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostLoginRoute = AuthenticatedPostLoginRouteImport.update({
  id: '/post-login',
  path: '/post-login',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupplyDriverRouteRoute =
  AuthenticatedSupplyDriverRouteRouteImport.update({
    id: '/supply-driver',
    path: '/supply-driver',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDriverRouteRoute =
  AuthenticatedDriverRouteRouteImport.update({
    id: '/driver',
    path: '/driver',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupplyDriverIndexRoute =
  AuthenticatedSupplyDriverIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSupplyDriverRouteRoute,
  } as any)
const AuthenticatedDriverIndexRoute =
  AuthenticatedDriverIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDriverRouteRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedSupplyDriverStopsRoute =
  AuthenticatedSupplyDriverStopsRouteImport.update({
    id: '/stops',
    path: '/stops',
    getParentRoute: () => AuthenticatedSupplyDriverRouteRoute,
  } as any)
const AuthenticatedSupplyDriverHistoryRoute =
  AuthenticatedSupplyDriverHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedSupplyDriverRouteRoute,
  } as any)
const AuthenticatedDriverOverviewRoute =
  AuthenticatedDriverOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedDriverRouteRoute,
  } as any)
const AuthenticatedDriverExpensesRoute =
  AuthenticatedDriverExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedDriverRouteRoute,
  } as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppRoutesRoute = AuthenticatedAppRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppProductsRoute =
  AuthenticatedAppProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPreordersRoute =
  AuthenticatedAppPreordersRouteImport.update({
    id: '/preorders',
    path: '/preorders',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppPaymentsRoute =
  AuthenticatedAppPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppLiveRoute = AuthenticatedAppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppExpensesRoute =
  AuthenticatedAppExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDispatchRoute =
  AuthenticatedAppDispatchRouteImport.update({
    id: '/dispatch',
    path: '/dispatch',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDeliveriesRoute =
  AuthenticatedAppDeliveriesRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCustomersRoute =
  AuthenticatedAppCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppBranchesRoute =
  AuthenticatedAppBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppBodegaRoute = AuthenticatedAppBodegaRouteImport.update({
  id: '/bodega',
  path: '/bodega',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppRoutesIndexRoute =
  AuthenticatedAppRoutesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppRoutesRoute,
  } as any)
const AuthenticatedAppRoutesRouteIdRoute =
  AuthenticatedAppRoutesRouteIdRouteImport.update({
    id: '/$routeId',
    path: '/$routeId',
    getParentRoute: () => AuthenticatedAppRoutesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/driver': typeof AuthenticatedDriverRouteRouteWithChildren
  '/supply-driver': typeof AuthenticatedSupplyDriverRouteRouteWithChildren
  '/post-login': typeof AuthenticatedPostLoginRoute
  '/app/bodega': typeof AuthenticatedAppBodegaRoute
  '/app/branches': typeof AuthenticatedAppBranchesRoute
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/deliveries': typeof AuthenticatedAppDeliveriesRoute
  '/app/dispatch': typeof AuthenticatedAppDispatchRoute
  '/app/expenses': typeof AuthenticatedAppExpensesRoute
  '/app/live': typeof AuthenticatedAppLiveRoute
  '/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/app/preorders': typeof AuthenticatedAppPreordersRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/routes': typeof AuthenticatedAppRoutesRouteWithChildren
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/driver/expenses': typeof AuthenticatedDriverExpensesRoute
  '/driver/overview': typeof AuthenticatedDriverOverviewRoute
  '/supply-driver/history': typeof AuthenticatedSupplyDriverHistoryRoute
  '/supply-driver/stops': typeof AuthenticatedSupplyDriverStopsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/driver/': typeof AuthenticatedDriverIndexRoute
  '/supply-driver/': typeof AuthenticatedSupplyDriverIndexRoute
  '/app/routes/$routeId': typeof AuthenticatedAppRoutesRouteIdRoute
  '/app/routes/': typeof AuthenticatedAppRoutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/post-login': typeof AuthenticatedPostLoginRoute
  '/app/bodega': typeof AuthenticatedAppBodegaRoute
  '/app/branches': typeof AuthenticatedAppBranchesRoute
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/deliveries': typeof AuthenticatedAppDeliveriesRoute
  '/app/dispatch': typeof AuthenticatedAppDispatchRoute
  '/app/expenses': typeof AuthenticatedAppExpensesRoute
  '/app/live': typeof AuthenticatedAppLiveRoute
  '/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/app/preorders': typeof AuthenticatedAppPreordersRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/driver/expenses': typeof AuthenticatedDriverExpensesRoute
  '/driver/overview': typeof AuthenticatedDriverOverviewRoute
  '/supply-driver/history': typeof AuthenticatedSupplyDriverHistoryRoute
  '/supply-driver/stops': typeof AuthenticatedSupplyDriverStopsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/driver': typeof AuthenticatedDriverIndexRoute
  '/supply-driver': typeof AuthenticatedSupplyDriverIndexRoute
  '/app/routes/$routeId': typeof AuthenticatedAppRoutesRouteIdRoute
  '/app/routes': typeof AuthenticatedAppRoutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/driver': typeof AuthenticatedDriverRouteRouteWithChildren
  '/_authenticated/supply-driver': typeof AuthenticatedSupplyDriverRouteRouteWithChildren
  '/_authenticated/post-login': typeof AuthenticatedPostLoginRoute
  '/_authenticated/app/bodega': typeof AuthenticatedAppBodegaRoute
  '/_authenticated/app/branches': typeof AuthenticatedAppBranchesRoute
  '/_authenticated/app/customers': typeof AuthenticatedAppCustomersRoute
  '/_authenticated/app/deliveries': typeof AuthenticatedAppDeliveriesRoute
  '/_authenticated/app/dispatch': typeof AuthenticatedAppDispatchRoute
  '/_authenticated/app/expenses': typeof AuthenticatedAppExpensesRoute
  '/_authenticated/app/live': typeof AuthenticatedAppLiveRoute
  '/_authenticated/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/_authenticated/app/preorders': typeof AuthenticatedAppPreordersRoute
  '/_authenticated/app/products': typeof AuthenticatedAppProductsRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/routes': typeof AuthenticatedAppRoutesRouteWithChildren
  '/_authenticated/app/users': typeof AuthenticatedAppUsersRoute
  '/_authenticated/driver/expenses': typeof AuthenticatedDriverExpensesRoute
  '/_authenticated/driver/overview': typeof AuthenticatedDriverOverviewRoute
  '/_authenticated/supply-driver/history': typeof AuthenticatedSupplyDriverHistoryRoute
  '/_authenticated/supply-driver/stops': typeof AuthenticatedSupplyDriverStopsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/driver/': typeof AuthenticatedDriverIndexRoute
  '/_authenticated/supply-driver/': typeof AuthenticatedSupplyDriverIndexRoute
  '/_authenticated/app/routes/$routeId': typeof AuthenticatedAppRoutesRouteIdRoute
  '/_authenticated/app/routes/': typeof AuthenticatedAppRoutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/driver'
    | '/supply-driver'
    | '/post-login'
    | '/app/bodega'
    | '/app/branches'
    | '/app/customers'
    | '/app/deliveries'
    | '/app/dispatch'
    | '/app/expenses'
    | '/app/live'
    | '/app/payments'
    | '/app/preorders'
    | '/app/products'
    | '/app/reports'
    | '/app/routes'
    | '/app/users'
    | '/driver/expenses'
    | '/driver/overview'
    | '/supply-driver/history'
    | '/supply-driver/stops'
    | '/app/'
    | '/driver/'
    | '/supply-driver/'
    | '/app/routes/$routeId'
    | '/app/routes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/post-login'
    | '/app/bodega'
    | '/app/branches'
    | '/app/customers'
    | '/app/deliveries'
    | '/app/dispatch'
    | '/app/expenses'
    | '/app/live'
    | '/app/payments'
    | '/app/preorders'
    | '/app/products'
    | '/app/reports'
    | '/app/users'
    | '/driver/expenses'
    | '/driver/overview'
    | '/supply-driver/history'
    | '/supply-driver/stops'
    | '/app'
    | '/driver'
    | '/supply-driver'
    | '/app/routes/$routeId'
    | '/app/routes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/driver'
    | '/_authenticated/supply-driver'
    | '/_authenticated/post-login'
    | '/_authenticated/app/bodega'
    | '/_authenticated/app/branches'
    | '/_authenticated/app/customers'
    | '/_authenticated/app/deliveries'
    | '/_authenticated/app/dispatch'
    | '/_authenticated/app/expenses'
    | '/_authenticated/app/live'
    | '/_authenticated/app/payments'
    | '/_authenticated/app/preorders'
    | '/_authenticated/app/products'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/routes'
    | '/_authenticated/app/users'
    | '/_authenticated/driver/expenses'
    | '/_authenticated/driver/overview'
    | '/_authenticated/supply-driver/history'
    | '/_authenticated/supply-driver/stops'
    | '/_authenticated/app/'
    | '/_authenticated/driver/'
    | '/_authenticated/supply-driver/'
    | '/_authenticated/app/routes/$routeId'
    | '/_authenticated/app/routes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/post-login': {
      id: '/_authenticated/post-login'
      path: '/post-login'
      fullPath: '/post-login'
      preLoaderRoute: typeof AuthenticatedPostLoginRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supply-driver': {
      id: '/_authenticated/supply-driver'
      path: '/supply-driver'
      fullPath: '/supply-driver'
      preLoaderRoute: typeof AuthenticatedSupplyDriverRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supply-driver/': {
      id: '/_authenticated/supply-driver/'
      path: '/'
      fullPath: '/supply-driver/'
      preLoaderRoute: typeof AuthenticatedSupplyDriverIndexRouteImport
      parentRoute: typeof AuthenticatedSupplyDriverRouteRoute
    }
    '/_authenticated/driver/': {
      id: '/_authenticated/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof AuthenticatedDriverIndexRouteImport
      parentRoute: typeof AuthenticatedDriverRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/supply-driver/stops': {
      id: '/_authenticated/supply-driver/stops'
      path: '/stops'
      fullPath: '/supply-driver/stops'
      preLoaderRoute: typeof AuthenticatedSupplyDriverStopsRouteImport
      parentRoute: typeof AuthenticatedSupplyDriverRouteRoute
    }
    '/_authenticated/supply-driver/history': {
      id: '/_authenticated/supply-driver/history'
      path: '/history'
      fullPath: '/supply-driver/history'
      preLoaderRoute: typeof AuthenticatedSupplyDriverHistoryRouteImport
      parentRoute: typeof AuthenticatedSupplyDriverRouteRoute
    }
    '/_authenticated/driver/overview': {
      id: '/_authenticated/driver/overview'
      path: '/overview'
      fullPath: '/driver/overview'
      preLoaderRoute: typeof AuthenticatedDriverOverviewRouteImport
      parentRoute: typeof AuthenticatedDriverRouteRoute
    }
    '/_authenticated/driver/expenses': {
      id: '/_authenticated/driver/expenses'
      path: '/expenses'
      fullPath: '/driver/expenses'
      preLoaderRoute: typeof AuthenticatedDriverExpensesRouteImport
      parentRoute: typeof AuthenticatedDriverRouteRoute
    }
    '/_authenticated/app/users': {
      id: '/_authenticated/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/routes': {
      id: '/_authenticated/app/routes'
      path: '/routes'
      fullPath: '/app/routes'
      preLoaderRoute: typeof AuthenticatedAppRoutesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/products': {
      id: '/_authenticated/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AuthenticatedAppProductsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/preorders': {
      id: '/_authenticated/app/preorders'
      path: '/preorders'
      fullPath: '/app/preorders'
      preLoaderRoute: typeof AuthenticatedAppPreordersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/payments': {
      id: '/_authenticated/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AuthenticatedAppPaymentsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/live': {
      id: '/_authenticated/app/live'
      path: '/live'
      fullPath: '/app/live'
      preLoaderRoute: typeof AuthenticatedAppLiveRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/expenses': {
      id: '/_authenticated/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AuthenticatedAppExpensesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/dispatch': {
      id: '/_authenticated/app/dispatch'
      path: '/dispatch'
      fullPath: '/app/dispatch'
      preLoaderRoute: typeof AuthenticatedAppDispatchRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/deliveries': {
      id: '/_authenticated/app/deliveries'
      path: '/deliveries'
      fullPath: '/app/deliveries'
      preLoaderRoute: typeof AuthenticatedAppDeliveriesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/customers': {
      id: '/_authenticated/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AuthenticatedAppCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/branches': {
      id: '/_authenticated/app/branches'
      path: '/branches'
      fullPath: '/app/branches'
      preLoaderRoute: typeof AuthenticatedAppBranchesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/bodega': {
      id: '/_authenticated/app/bodega'
      path: '/bodega'
      fullPath: '/app/bodega'
      preLoaderRoute: typeof AuthenticatedAppBodegaRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/routes/': {
      id: '/_authenticated/app/routes/'
      path: '/'
      fullPath: '/app/routes/'
      preLoaderRoute: typeof AuthenticatedAppRoutesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoutesRoute
    }
    '/_authenticated/app/routes/$routeId': {
      id: '/_authenticated/app/routes/$routeId'
      path: '/$routeId'
      fullPath: '/app/routes/$routeId'
      preLoaderRoute: typeof AuthenticatedAppRoutesRouteIdRouteImport
      parentRoute: typeof AuthenticatedAppRoutesRoute
    }
  }
}

interface AuthenticatedAppRoutesRouteChildren {
  AuthenticatedAppRoutesRouteIdRoute: typeof AuthenticatedAppRoutesRouteIdRoute
  AuthenticatedAppRoutesIndexRoute: typeof AuthenticatedAppRoutesIndexRoute
}

const AuthenticatedAppRoutesRouteChildren: AuthenticatedAppRoutesRouteChildren =
  {
    AuthenticatedAppRoutesRouteIdRoute: AuthenticatedAppRoutesRouteIdRoute,
    AuthenticatedAppRoutesIndexRoute: AuthenticatedAppRoutesIndexRoute,
  }

const AuthenticatedAppRoutesRouteWithChildren =
  AuthenticatedAppRoutesRoute._addFileChildren(
    AuthenticatedAppRoutesRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppBodegaRoute: typeof AuthenticatedAppBodegaRoute
  AuthenticatedAppBranchesRoute: typeof AuthenticatedAppBranchesRoute
  AuthenticatedAppCustomersRoute: typeof AuthenticatedAppCustomersRoute
  AuthenticatedAppDeliveriesRoute: typeof AuthenticatedAppDeliveriesRoute
  AuthenticatedAppDispatchRoute: typeof AuthenticatedAppDispatchRoute
  AuthenticatedAppExpensesRoute: typeof AuthenticatedAppExpensesRoute
  AuthenticatedAppLiveRoute: typeof AuthenticatedAppLiveRoute
  AuthenticatedAppPaymentsRoute: typeof AuthenticatedAppPaymentsRoute
  AuthenticatedAppPreordersRoute: typeof AuthenticatedAppPreordersRoute
  AuthenticatedAppProductsRoute: typeof AuthenticatedAppProductsRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppRoutesRoute: typeof AuthenticatedAppRoutesRouteWithChildren
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppBodegaRoute: AuthenticatedAppBodegaRoute,
  AuthenticatedAppBranchesRoute: AuthenticatedAppBranchesRoute,
  AuthenticatedAppCustomersRoute: AuthenticatedAppCustomersRoute,
  AuthenticatedAppDeliveriesRoute: AuthenticatedAppDeliveriesRoute,
  AuthenticatedAppDispatchRoute: AuthenticatedAppDispatchRoute,
  AuthenticatedAppExpensesRoute: AuthenticatedAppExpensesRoute,
  AuthenticatedAppLiveRoute: AuthenticatedAppLiveRoute,
  AuthenticatedAppPaymentsRoute: AuthenticatedAppPaymentsRoute,
  AuthenticatedAppPreordersRoute: AuthenticatedAppPreordersRoute,
  AuthenticatedAppProductsRoute: AuthenticatedAppProductsRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppRoutesRoute: AuthenticatedAppRoutesRouteWithChildren,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedDriverRouteRouteChildren {
  AuthenticatedDriverExpensesRoute: typeof AuthenticatedDriverExpensesRoute
  AuthenticatedDriverOverviewRoute: typeof AuthenticatedDriverOverviewRoute
  AuthenticatedDriverIndexRoute: typeof AuthenticatedDriverIndexRoute
}

const AuthenticatedDriverRouteRouteChildren: AuthenticatedDriverRouteRouteChildren =
  {
    AuthenticatedDriverExpensesRoute: AuthenticatedDriverExpensesRoute,
    AuthenticatedDriverOverviewRoute: AuthenticatedDriverOverviewRoute,
    AuthenticatedDriverIndexRoute: AuthenticatedDriverIndexRoute,
  }

const AuthenticatedDriverRouteRouteWithChildren =
  AuthenticatedDriverRouteRoute._addFileChildren(
    AuthenticatedDriverRouteRouteChildren,
  )

interface AuthenticatedSupplyDriverRouteRouteChildren {
  AuthenticatedSupplyDriverHistoryRoute: typeof AuthenticatedSupplyDriverHistoryRoute
  AuthenticatedSupplyDriverStopsRoute: typeof AuthenticatedSupplyDriverStopsRoute
  AuthenticatedSupplyDriverIndexRoute: typeof AuthenticatedSupplyDriverIndexRoute
}

const AuthenticatedSupplyDriverRouteRouteChildren: AuthenticatedSupplyDriverRouteRouteChildren =
  {
    AuthenticatedSupplyDriverHistoryRoute:
      AuthenticatedSupplyDriverHistoryRoute,
    AuthenticatedSupplyDriverStopsRoute: AuthenticatedSupplyDriverStopsRoute,
    AuthenticatedSupplyDriverIndexRoute: AuthenticatedSupplyDriverIndexRoute,
  }

const AuthenticatedSupplyDriverRouteRouteWithChildren =
  AuthenticatedSupplyDriverRouteRoute._addFileChildren(
    AuthenticatedSupplyDriverRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedDriverRouteRoute: typeof AuthenticatedDriverRouteRouteWithChildren
  AuthenticatedSupplyDriverRouteRoute: typeof AuthenticatedSupplyDriverRouteRouteWithChildren
  AuthenticatedPostLoginRoute: typeof AuthenticatedPostLoginRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedDriverRouteRoute: AuthenticatedDriverRouteRouteWithChildren,
  AuthenticatedSupplyDriverRouteRoute:
    AuthenticatedSupplyDriverRouteRouteWithChildren,
  AuthenticatedPostLoginRoute: AuthenticatedPostLoginRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
